version: '3'
services:
  app1:
    build: .
    ports:
      - 81:3021
    env_file:
      - .env
  # app2:
  #   build: .
  #   ports:
  #     - 82:3021
  #   env_file:
  #     - .env
  # app3:
  #   build: .
  #   ports:
  #     - 83:3021
  #   env_file:
  #     - .env
  redis:
    image: redis
    hostname: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      # - app2
      # - app3
volumes:
  redis_data: