name: Continuous Integration

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: npm ci
      - run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: npm ci
      - run: npm test
        env:
          DATABASE_NAME: "atelier_products"
          DATABASE_HOST: "localhost"
          RAW_DATA_DIR: "/Users/thomasspradling/HackReactor/products-system-sdc/database/import_data/raw_data"

          SERVER_PORT: 3000

          POSTGRES_USER: "postgres"
          POSTGRES_PORT: 5432